### PR TITLE
Sync AST

### PR DESCRIPTION
**Pull request by bdahse**

### CODE REVIEW

**Comment by bdahse** [comment]
I still need to do the same exercise on guards, so this is not quite ready yet.

**Comment by bdahse** [comment]
It's not pretty but it works :)

**Comment by magnus-madsen** [comment]
Ready for review?

**Comment by bdahse** [comment]
> 
> 
> Ready for review?

Yep.

**Comment by magnus-madsen** [comment]
I did not have any comments, so I merged it 👍

**Pull request merged**
