### PR TITLE
Pretty printing RAM programs

### PR DESCRIPTION
**Pull request by bdahse**

### CODE REVIEW

**Comment by bdahse** [comment]
The prettyprinter made me aware of some codegen bugs in the compiler. Now those are fixed and we can evaluate both test programs AND get the right result :)

**Comment by bdahse** [comment]
Does Flix have multiline strings?

**Comment by magnus-madsen** [comment]
> 
> 
> Does Flix have multiline strings?

Not yet, unfortunately.

**Comment by bdahse** [comment]
This should be ready to merge now.

**Comment by magnus-madsen** [comment]
Merged! Excellent!

**Pull request merged**
